# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check commit message
      run: |
        MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
        if [[ $MESSAGE == "docs:"* ]]; then
          echo "Commit message starts with 'docs:', skipping job"
          exit 0
        fi
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission on generateGitProperties
      run: chmod +x ./app/generateGitProperties.sh
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: ps3netsrv-android
        path: app/build/outputs/apk/debug/app-debug.apk
